import { Box, Button, FormControl, FormLabel, Input, Switch, VStack, Menu, MenuButton, MenuList, MenuItem } from "@chakra-ui/react";
import { MdChevronDown as ChevronDownIcon } from "react-icons/md";

const Share = () => {
  const autoGeneratedLink = "https://example.com/auto-generated-link"; // Replace with actual logic

  return (
    <Box p={4}>
      <VStack spacing={4} align="stretch">
        <FormControl id="webpage-link">
          <FormLabel>WebPage Link</FormLabel>
          <Input type="text" />
        </FormControl>
        <FormControl id="public-private">
          <FormLabel>Public / Private</FormLabel>
          <Switch />
        </FormControl>
        <Menu>
          <MenuButton as={Button} rightIcon={<ChevronDownIcon />}>
            Share
          </MenuButton>
          <MenuList>
            <MenuItem onClick={() => navigator.clipboard.writeText(autoGeneratedLink)}>Copy Auto-Generated Link</MenuItem>
          </MenuList>
        </Menu>
      </VStack>
    </Box>
  );
};

export default Share;